services:
  joo-coin-db:
    image: mysql:latest
    container_name: joo-coin-db
    environment:
      MYSQL_DATABASE: joo_coin_db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      # - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - joo-coin

volumes:
  db-data:

networks:
  joo-coin:
