[project]
name = "joo-coin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "openai>=2.7.1",
    "python-dotenv>=1.2.1",
    "pyupbit>=0.2.34",
]
